application:
  name: rep2recall
  project: rep2recall
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  custom_domains:
  - branch: qovery-dev
    domain: dev.rep2recall.net
  routes:
  - application_name: rep2recall
    paths:
    - /
