version: '3'

services: 
  mongodb:
    image: mongo
    # ports:
    #   - 27017:27017
    volumes: 
      - './db:/data/db'
  server:
    build: .
    image: patarapolw/rep2recall
    ports: 
      - 80:8080
    depends_on: 
      - mongodb
    env_file: 
      - .env
    environment: 
      - MONGO_URI=mongodb://mongodb:27017/rep2recall