CREATE TABLE "preset" (
  "id"          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId"      UUID NOT NULL REFERENCES "user"("id"),
  "shortId"     TEXT NOT NULL,
  "q"           TEXT NOT NULL,
  "name"        TEXT NOT NULL,
  "status"      JSONB NOT NULL,
  "selected"    JSONB NOT NULL,
  "opened"      JSONB NOT NULL,
  "createdAt"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"   TIMESTAMP,
  UNIQUE ("userId", "shortId")
);

CREATE TRIGGER "t_preset_updatedAt"
  BEFORE UPDATE ON "preset"
  FOR EACH ROW
  EXECUTE PROCEDURE "f_updatedAt"();
